latex_dir = "../../Tesi_Andrea_Grande/Chapter_4/";
subdirs = [ ...
    "wing_downwash_1/", ...
    "wing_downwash_2/",...
        ];

% create folders (skipped if folders exist)
for i=1:length(subdirs)
    [status, msg] = mkdir(strcat(latex_dir, subdirs(i)));
end

for i=1:length(subdirs)
    status = copyfile( ...
        strcat(subdirs(i),"data.tex"), ...
        strcat(latex_dir, subdirs(i), "data.tex") ...
    );
 status = copyfile( ...
        strcat(subdirs(i),"data_b.tex"), ...
        strcat(latex_dir, subdirs(i), "data_b.tex") ...
    );
 status = copyfile( ...
        strcat(subdirs(i),"data_c.tex"), ...
        strcat(latex_dir, subdirs(i), "data_c.tex") ...
    );
    status = copyfile( ...
        strcat(subdirs(i),"dataset.txt"), ...
        strcat(latex_dir, subdirs(i), "dataset.txt") ...
    );
end