latex_dir = "../../Tesi_Andrea_Grande/Chapter_2/";
subdirs = [ ...
    "geometric_characteristics_of_a_straight_wing/", ...
    "geometric_characteristics_of_a_straight_and_tapered_wing/",...
    "geometric_characteristics_of_a_wing_with_arrow_not_null/",...
    "geometric_characteristics_of_a_cranked_wing/",...
    "equivalent_plan_form_of_a_cranked_wing/",...
    "zero_lift_angle_of_a_finished_wing/",...
    "zero_lift_angle_of_a_cranked_wing/",...
    "zero_lift_angle_graphic_method/",...
    "lift_gradient_of_a_finite_wing/",...
    "lift_gradient_aspect_ratio_effect/",...
    "lift_gradient_polhamus_formula/",...
    "aerodynamic_center_of_a_finite_wing/",...
    "aerodynamic_center_of_a_cranked_wing/",...
    "pitching_moment/",...
    "pitching_moment_two/",...
    ];

% create folders (skipped if folders exist)
for i=1:length(subdirs)
    [status, msg] = mkdir(strcat(latex_dir, subdirs(i)));
end

for i=1:length(subdirs)
    status = copyfile( ...
        strcat(subdirs(i),"data.tex"), ...
        strcat(latex_dir, subdirs(i), "data.tex") ...
    );
 status = copyfile( ...
        strcat(subdirs(i),"data_b.tex"), ...
        strcat(latex_dir, subdirs(i), "data_b.tex") ...
    );
 status = copyfile( ...
        strcat(subdirs(i),"data_c.tex"), ...
        strcat(latex_dir, subdirs(i), "data_c.tex") ...
    );
    status = copyfile( ...
        strcat(subdirs(i),"dataset.txt"), ...
        strcat(latex_dir, subdirs(i), "dataset.txt") ...
    );
end

