latex_dir = "../../Tesi_Andrea_Grande/Chapter_1/";
subdirs = [ ...
    "characteristics_of_the_air_at_a_certain_altitude/", ...
    "equivalent_airspeed_basic_3/" ...
    "aerodynamic_angles_1/" ...
    ];

% create folders (skipped if folders exist)
for i=1:length(subdirs)
    [status, msg] = mkdir(strcat(latex_dir, subdirs(i)));
end

for i=1:length(subdirs)
    status = copyfile( ...
        strcat(subdirs(i),"data.tex"), ...
        strcat(latex_dir, subdirs(i), "data.tex") ...
    );
end
